# Generated by Django 4.1.4 on 2023-01-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyTransact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
