# Generated by Django 4.1.4 on 2023-01-02 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MoneyTransact', '0002_alter_balance_amount_alter_balance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('Rs', 'Rupees'), ('$', 'Dollar'), ('o/w', 'Others')], default='Rs', max_length=3)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
                ('giver', models.ManyToManyField(related_name='giver', to=settings.AUTH_USER_MODEL)),
                ('taker', models.ManyToManyField(related_name='taker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
