# Generated by Django 4.1.4 on 2023-01-02 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MoneyTransact', '0003_transaction_delete_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='giver',
        ),
        migrations.AddField(
            model_name='transaction',
            name='giver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='giver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
