# Generated by Django 4.1.4 on 2023-01-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyTransact', '0005_transaction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
