# Generated by Django 4.1.4 on 2023-01-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyTransact', '0007_transaction_date_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
